<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $smartphones = Category::where('name', 'Smartphone')->first();
        $laptops = Category::where('name', 'Laptop')->first();
        $tablets = Category::where('name', 'Tablet')->first();
        $audio = Category::where('name', 'Audio')->first();
        $gaming = Category::where('name', 'Gaming')->first();
        $accessories = Category::where('name', 'Accessories')->first();

        $products = [
            [
                'category_id' => $smartphones->id,
                'name' => 'iPhone 15 Pro',
                'sku' => 'IP15-PRO-128',
                'description' => 'Latest iPhone 15 Pro with A17 Pro chip',
                'short_description' => 'Premium smartphone with advanced camera system',
                'price' => 15999000,
                'compare_price' => 17999000,
                'stock_quantity' => 25,
                'brand' => 'Apple',
                'warranty' => '1 Year International Warranty',
                'is_featured' => true,
                'image' => 'products/iphone-15-pro.jpg',
            ],
            [
                'category_id' => $smartphones->id,
                'name' => 'Samsung Galaxy S24',
                'sku' => 'SAM-S24-256',
                'description' => 'Galaxy S24 with AI-powered photography',
                'short_description' => 'Flagship Android smartphone',
                'price' => 12999000,
                'compare_price' => 14999000,
                'stock_quantity' => 30,
                'brand' => 'Samsung',
                'warranty' => '1 Year Local Warranty',
                'is_featured' => true,
                'image' => 'products/samsung-galaxy-s24.jpg',
            ],
            [
                'category_id' => $laptops->id,
                'name' => 'MacBook Air M3',
                'sku' => 'MBA-M3-256',
                'description' => 'MacBook Air with M3 chip for ultimate performance',
                'short_description' => 'Ultra-thin laptop with all-day battery',
                'price' => 18999000,
                'compare_price' => 20999000,
                'stock_quantity' => 15,
                'brand' => 'Apple',
                'warranty' => '1 Year International Warranty',
                'is_featured' => true,
                'image' => 'products/macbook-air-m3.jpg',
            ],
            [
                'category_id' => $tablets->id,
                'name' => 'iPad Pro 12.9"',
                'sku' => 'IPAD-PRO-129',
                'description' => 'iPad Pro with M2 chip and Liquid Retina XDR display',
                'short_description' => 'Professional tablet for creative work',
                'price' => 16999000,
                'stock_quantity' => 20,
                'brand' => 'Apple',
                'warranty' => '1 Year International Warranty',
                'image' => 'products/ipad-pro-129.jpg',
            ],
            [
                'category_id' => $smartphones->id,
                'name' => 'Xiaomi 14 Ultra',
                'sku' => 'XIA-14-ULT',
                'description' => 'Xiaomi 14 Ultra with Leica cameras and Snapdragon 8 Gen 3',
                'short_description' => 'Photography-focused flagship smartphone',
                'price' => 13999000,
                'compare_price' => 15999000,
                'stock_quantity' => 18,
                'brand' => 'Xiaomi',
                'warranty' => '1 Year Local Warranty',
                'is_featured' => true,
                'image' => 'products/xiaomi-14-ultra.jpg',
            ],
            [
                'category_id' => $laptops->id,
                'name' => 'ASUS ROG Zephyrus G14',
                'sku' => 'ASUS-ROG-G14',
                'description' => 'Gaming laptop with AMD Ryzen 9 and RTX 4070',
                'short_description' => 'Compact gaming laptop with high performance',
                'price' => 24999000,
                'compare_price' => 27999000,
                'stock_quantity' => 12,
                'brand' => 'ASUS',
                'warranty' => '2 Years International Warranty',
                'is_featured' => false,
                'image' => 'products/asus-rog-g14.jpg',
            ],
            [
                'category_id' => $tablets->id,
                'name' => 'Samsung Galaxy Tab S9',
                'sku' => 'SAM-TAB-S9',
                'description' => 'Galaxy Tab S9 with S Pen and Dynamic AMOLED display',
                'short_description' => 'Premium Android tablet for productivity',
                'price' => 9999000,
                'compare_price' => 11999000,
                'stock_quantity' => 22,
                'brand' => 'Samsung',
                'warranty' => '1 Year Local Warranty',
                'is_featured' => false,
                'image' => 'products/samsung-tab-s9.jpg',
            ],
            [
                'category_id' => $smartphones->id,
                'name' => 'Google Pixel 8 Pro',
                'sku' => 'GOO-PIX-8PRO',
                'description' => 'Google Pixel 8 Pro with Tensor G3 and AI features',
                'short_description' => 'Pure Android experience with advanced AI',
                'price' => 11999000,
                'compare_price' => 13999000,
                'stock_quantity' => 16,
                'brand' => 'Google',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/google-pixel-8-pro.jpg',
            ],
            [
                'category_id' => $laptops->id,
                'name' => 'Dell XPS 13',
                'sku' => 'DELL-XPS-13',
                'description' => 'Dell XPS 13 with Intel Core i7 and InfinityEdge display',
                'short_description' => 'Premium ultrabook for professionals',
                'price' => 19999000,
                'compare_price' => 22999000,
                'stock_quantity' => 14,
                'brand' => 'Dell',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/dell-xps-13.jpg',
            ],
            [
                'category_id' => $smartphones->id,
                'name' => 'OnePlus 12',
                'sku' => 'ONE-12-256',
                'description' => 'OnePlus 12 with Snapdragon 8 Gen 3 and 120Hz display',
                'short_description' => 'Flagship killer with premium features',
                'price' => 10999000,
                'compare_price' => 12999000,
                'stock_quantity' => 28,
                'brand' => 'OnePlus',
                'warranty' => '1 Year Local Warranty',
                'is_featured' => false,
                'image' => 'products/oneplus-12.jpg',
            ],
            [
                'category_id' => $tablets->id,
                'name' => 'iPad Air 5th Gen',
                'sku' => 'IPAD-AIR-5',
                'description' => 'iPad Air with M1 chip and 10.9-inch Liquid Retina display',
                'short_description' => 'Versatile tablet for work and play',
                'price' => 8999000,
                'compare_price' => 10999000,
                'stock_quantity' => 26,
                'brand' => 'Apple',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/ipad-air-5.jpg',
            ],
            [
                'category_id' => $laptops->id,
                'name' => 'HP Spectre x360',
                'sku' => 'HP-SPEC-X360',
                'description' => 'HP Spectre x360 2-in-1 with Intel Core i7 and OLED display',
                'short_description' => 'Convertible laptop with premium design',
                'price' => 21999000,
                'compare_price' => 24999000,
                'stock_quantity' => 10,
                'brand' => 'HP',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/hp-spectre-x360.jpg',
            ],
            [
                'category_id' => $smartphones->id,
                'name' => 'Realme GT 5 Pro',
                'sku' => 'REA-GT5-PRO',
                'description' => 'Realme GT 5 Pro with Snapdragon 8 Gen 3 and 144Hz display',
                'short_description' => 'Gaming smartphone with flagship performance',
                'price' => 8999000,
                'compare_price' => 10999000,
                'stock_quantity' => 35,
                'brand' => 'Realme',
                'warranty' => '1 Year Local Warranty',
                'is_featured' => false,
                'image' => 'products/realme-gt5-pro.jpg',
            ],
            [
                'category_id' => $laptops->id,
                'name' => 'Lenovo ThinkPad X1 Carbon',
                'sku' => 'LEN-X1-CARBON',
                'description' => 'ThinkPad X1 Carbon with Intel Core i7 and military-grade durability',
                'short_description' => 'Business laptop with legendary reliability',
                'price' => 23999000,
                'compare_price' => 26999000,
                'stock_quantity' => 8,
                'brand' => 'Lenovo',
                'warranty' => '3 Years International Warranty',
                'is_featured' => false,
                'image' => 'products/lenovo-x1-carbon.jpg',
            ],
            [
                'category_id' => $tablets->id,
                'name' => 'Microsoft Surface Pro 9',
                'sku' => 'MS-SURF-PRO9',
                'description' => 'Surface Pro 9 with Intel Core i7 and detachable keyboard',
                'short_description' => '2-in-1 tablet that replaces your laptop',
                'price' => 17999000,
                'compare_price' => 19999000,
                'stock_quantity' => 13,
                'brand' => 'Microsoft',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/surface-pro-9.jpg',
            ],
            [
                'category_id' => $audio->id,
                'name' => 'AirPods Pro 2nd Gen',
                'sku' => 'AIRPODS-PRO2',
                'description' => 'AirPods Pro with Active Noise Cancellation and Spatial Audio',
                'short_description' => 'Premium wireless earbuds with ANC',
                'price' => 3999000,
                'compare_price' => 4499000,
                'stock_quantity' => 40,
                'brand' => 'Apple',
                'warranty' => '1 Year International Warranty',
                'is_featured' => true,
                'image' => 'products/airpods-pro-2.jpg',
            ],
            [
                'category_id' => $gaming->id,
                'name' => 'PlayStation 5',
                'sku' => 'PS5-CONSOLE',
                'description' => 'PlayStation 5 console with DualSense controller',
                'short_description' => 'Next-gen gaming console',
                'price' => 7999000,
                'compare_price' => 8999000,
                'stock_quantity' => 8,
                'brand' => 'Sony',
                'warranty' => '1 Year Local Warranty',
                'is_featured' => true,
                'image' => 'products/playstation-5.jpg',
            ],
            [
                'category_id' => $accessories->id,
                'name' => 'MagSafe Charger',
                'sku' => 'MAGSAFE-CHAR',
                'description' => 'Wireless MagSafe charger for iPhone 12 and later',
                'short_description' => 'Fast wireless charging for iPhone',
                'price' => 699000,
                'compare_price' => 899000,
                'stock_quantity' => 60,
                'brand' => 'Apple',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/magsafe-charger.jpg',
            ],
            [
                'category_id' => $audio->id,
                'name' => 'Sony WH-1000XM5',
                'sku' => 'SONY-WH1000XM5',
                'description' => 'Premium noise-canceling headphones with 30-hour battery',
                'short_description' => 'Industry-leading noise cancellation',
                'price' => 4999000,
                'compare_price' => 5999000,
                'stock_quantity' => 25,
                'brand' => 'Sony',
                'warranty' => '1 Year International Warranty',
                'is_featured' => true,
                'image' => 'products/sony-wh1000xm5.jpg',
            ],
            [
                'category_id' => $gaming->id,
                'name' => 'Xbox Series X',
                'sku' => 'XBOX-SERIES-X',
                'description' => 'Xbox Series X console with 1TB storage',
                'short_description' => 'Most powerful Xbox ever',
                'price' => 7499000,
                'compare_price' => 8499000,
                'stock_quantity' => 12,
                'brand' => 'Microsoft',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/xbox-series-x.jpg',
            ],
            [
                'category_id' => $accessories->id,
                'name' => 'Anker PowerBank 20000mAh',
                'sku' => 'ANKER-PB20K',
                'description' => 'High-capacity power bank with fast charging',
                'short_description' => 'Portable charger for all devices',
                'price' => 899000,
                'compare_price' => 1199000,
                'stock_quantity' => 45,
                'brand' => 'Anker',
                'warranty' => '18 Months International Warranty',
                'is_featured' => false,
                'image' => 'products/anker-powerbank.jpg',
            ],
            [
                'category_id' => $gaming->id,
                'name' => 'Nintendo Switch OLED',
                'sku' => 'NSW-OLED',
                'description' => 'Nintendo Switch with vibrant OLED screen',
                'short_description' => 'Portable gaming console with OLED',
                'price' => 4999000,
                'compare_price' => 5499000,
                'stock_quantity' => 18,
                'brand' => 'Nintendo',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/nintendo-switch-oled.jpg',
            ],
            [
                'category_id' => $audio->id,
                'name' => 'Bose QuietComfort 45',
                'sku' => 'BOSE-QC45',
                'description' => 'Comfortable noise-canceling headphones',
                'short_description' => 'All-day comfort with premium sound',
                'price' => 4499000,
                'compare_price' => 5199000,
                'stock_quantity' => 20,
                'brand' => 'Bose',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/bose-qc45.jpg',
            ],
            [
                'category_id' => $accessories->id,
                'name' => 'Logitech MX Master 3S',
                'sku' => 'LOGI-MX3S',
                'description' => 'Advanced wireless mouse for productivity',
                'short_description' => 'Precision mouse for professionals',
                'price' => 1399000,
                'compare_price' => 1599000,
                'stock_quantity' => 30,
                'brand' => 'Logitech',
                'warranty' => '1 Year International Warranty',
                'is_featured' => false,
                'image' => 'products/logitech-mx-master-3s.jpg',
            ],
        ];

        foreach ($products as $productData) {
            // Extract image path
            $imagePath = $productData['image'];
            unset($productData['image']);

            // Generate slug if not provided
            if (!isset($productData['slug'])) {
                $productData['slug'] = Str::slug($productData['name']);
            }

            // Create product
            $product = Product::create($productData);

            // Create product image
            ProductImage::create([
                'product_id' => $product->id,
                'image_path' => $imagePath,
                'alt_text' => $product->name,
                'is_primary' => true,
                'sort_order' => 1,
            ]);
        }
    }
}